  name: Lmop Module Builder

  on:
    push:
      branches:
        - lmop-release

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Zip Files
          working-directory: ./lmop/
          run: zip -r ./world.zip ./*

        - name: Get Version
          shell: bash
          id: get-version
          run: echo "::set-output name=version::$(node ./.github/workflows/get-version-lmop.js)"

        - name: Create Release
          id: create-release
          uses: ncipollo/release-action@v1
          with:
            allowUpdates: true
            name: lmop ${{ steps.get-version.outputs.version }}
            draft: false
            prerelease: false
            token: ${{secrets.GITHUB_TOKEN}}
            artifacts: './lmop/world.zip, ./lmop/world.json'
            tag: lmop_${{ steps.get-version.outputs.version }}