  name: The Marsh Module Builder

  on:
    push:
      branches:
        - the-marsh-release

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Zip Files
          working-directory: ./the-marsh/
          run: zip -r ./world.zip ./*

        - name: Get Version
          shell: bash
          id: get-version
          run: echo "::set-output name=version::$(node ./.github/workflows/the-marsh-get-version.js)"

        - name: Create Release
          id: create-release
          uses: ncipollo/release-action@v1
          with:
            allowUpdates: true
            name: the-marsh ${{ steps.get-version.outputs.version }}
            draft: false
            prerelease: false
            token: ${{secrets.GITHUB_TOKEN}}
            artifacts: './the-marsh/world.zip, ./the-marsh/world.json'
            tag: the-marsh_${{ steps.get-version.outputs.version }}