  name: WD-Dotmm Module Builder

  on:
    push:
      branches:
        - wd-dotmm-release

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Zip Files
          working-directory: ./wd-dotmm/
          run: zip -r ./world.zip ./*

        - name: Get Version
          shell: bash
          id: get-version
          run: echo "::set-output name=version::$(node ./.github/workflows/wd-dotmm-get-version.js)"

        - name: Create Release
          id: create-release
          uses: ncipollo/release-action@v1
          with:
            allowUpdates: true
            name: wd-dotmm ${{ steps.get-version.outputs.version }}
            draft: false
            prerelease: false
            token: ${{secrets.GITHUB_TOKEN}}
            artifacts: './wd-dotmm/world.zip, ./wd-dotmm/world.json'
            tag: wd-dotmm_${{ steps.get-version.outputs.version }}